name: RCC
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.0=py314hd8ed1ab_102
  - debugpy=1.8.17=py314h8b4fd5f_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyh0d26453_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314hc5dbbe4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.14.0=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python_abi=3.14=2_cp314
  - pywin32=311=py314h8f8f202_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py314h5a2d7ad_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - aniso8601==10.0.1
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mistune==3.1.4
      - narwhals==2.12.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.6
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numpy==2.3.5
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - plotly==6.5.0
      - prometheus-client==0.23.1
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - rdflib==7.5.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.29.0
      - scipy==1.16.3
      - send2trash==1.8.3
      - setuptools==80.9.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - tabulate==0.9.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - triplets==0.0.17
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
prefix: C:\Users\Kevin\miniconda3\envs\RCC
